### ISSUE TITLE
Proposed small improvement: use entered domain name as "salt"

### ISSUE THREAD

**Issue by Wikinaut** [pinae/passwordGenerator-python#5]
see https://twitter.com/FredericJacobs/status/634354231152128001 and replies

> Idea: Web browsers should systematically salt passwords on a per-domain basis to mitigate cross-domain password reuse.

At least, some 16 or more characters of the domain name could be easily used as salt, depending on the limitations (if exist) of the Python-PBKDF2 function, see https://docs.python.org/3/library/hashlib.html 

> "salt should be about 16 or more bytes from a proper source"

**Comment by Wikinaut** [comment]
let line 28 become 
`hashed_bytes = pbkdf2_hmac('sha512', hash_string.encode('utf-8'), domain.encode('utf-8'), 4096)` 

and delete line 11.

**Comment by 607011** [comment]
@Wikinaut , `domain` is already concatenated with `master_password` giving `hash_string`.

A "proper source" is meant to be a random source. But that would lead to non-deterministic passwords. Unless ctSESAM-python is not able so securely store the domain parameters (name, user name, iterations, password length, salt) a "proper" salt wouldn't make sense.

**Comment by Wikinaut** [comment]
But my proposal saves one line (salt="pepper") code without decreasing security of the generated passwds.

**Comment by pinae** [comment]
See https://github.com/pinae/ctSESAM-python-memorizing for an even better solution.
