### ISSUE TITLE
Masterpasswort wird nicht angenommen

### ISSUE THREAD

**Issue by dirri** [pinae/passwordGenerator-python#6]
python ctSESAM.py 
Masterpasswort: einsuperpassword
Traceback (most recent call last):
  File "ctSESAM.py", line 22, in <module>
    master_password = input("Masterpasswort: ")
  File "<string>", line 1, in <module>
NameError: name 'einsuperpassword' is not defined

Was ist das Problem?

**Comment by pinae** [comment]
Ist der Code in irgend einer Weise verändert? Wenn ja, müsste ich den echten Code sehen, um das einschätzen zu können.

Welche Python-Version und welches Betriebssystem ist das denn?

**Comment by dirri** [comment]
Ist der downloaded code unverändert. Ubuntu 15.10 Python 2.7.10
Sorry liegt an der 2 er python version.. _schäm_

**Comment by pinae** [comment]
Bei der Umstellung von Python2 zu Python3 wurde `raw_input` in `input` umbenannt. In Python2 gab es auch ein `input`, das aber folgendes gemacht hat: https://docs.python.org/2/library/functions.html#input

**Comment by 607011** [comment]
Wie wäre es, den Code auch Python-2-tauglich zu machen? Das wäre doch ein Klacks. Soll ich?

**Comment by pinae** [comment]
Wenn du magst. Machst du einen Pull-Request?
